name: 'dwh'
version: '1.0'
config-version: 2

profile: 'dwh'

model-paths: ['models']
seed-paths: ['seeds', '../../external_data']

target-path: 'target'

models:
  dwh:
    bronze:
      materialized: table
    silver:
      materialized: table
    gold:
      materialized: table
