version: 2
models:
  - name: stg_player_stats
    description: Raw season averages loaded from the balldontlie API.
  - name: player_stats
    description: Cleaned player statistics for the selected season.
  - name: player_efficiency
    description: Player efficiency calculated from season averages.
    columns:
      - name: efficiency
        tests:
          - not_null
