version: '3.8'
services:
  dwh:
    build: .
    volumes:
      - ./data:/app/data
    command: dagster dev -m dagster_pipeline --host 0.0.0.0
    ports:
      - "3000:3000"
    environment:
      DBT_PROFILES_DIR: /app/mini_dwh_dbt

  docs:
    build: .
    command: bash -c "dbt docs generate && dbt docs serve --port 8081 --address 0.0.0.0"
    volumes:
      - ./data:/app/data
    ports:
      - "8081:8081"
    environment:
      DBT_PROFILES_DIR: /app/mini_dwh_dbt
