version: '3.8'
services:
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
  dwh:
    build: .
    volumes:
      - ./data:/app/data
    command: dagster dev -m dagster_pipeline --host 0.0.0.0
    ports:
      - "3000:3000"
    environment:
      DBT_PROFILES_DIR: /app/dbt
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: warehouse

  superset_db:
    image: postgres:13
    environment:
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_DB: superset
    volumes:
      - superset_db:/var/lib/postgresql/data

  superset_cache:
    image: redis:latest

  superset:
    image: apache/superset:latest
    depends_on:
      - superset_db
      - superset_cache
    environment:
      SUPERSET_SECRET_KEY: superset-secret
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://superset:superset@superset_db:5432/superset
      REDIS_HOST: superset_cache
    ports:
      - "8080:8088"

  docs:
    build: .
    working_dir: /app/dbt
    command: bash -c "dbt docs generate && dbt docs serve --port 8081 --host 0.0.0.0"

    volumes:
      - ./data:/app/data
    ports:
      - "8081:8081"
    environment:
      DBT_PROFILES_DIR: /app/dbt

volumes:
  superset_db:
  minio_data:
  superset_cache:
