version: '3.8'
services:
  dwh:
    build: .
    volumes:
      - ./data:/app/data
    command: dagster dev -m dagster_pipeline --host 0.0.0.0
    ports:
      - "3000:3000"
    environment:
      DBT_PROFILES_DIR: /app/dbt

  lightdash_db:
    image: postgres:13
    environment:
      POSTGRES_USER: lightdash
      POSTGRES_PASSWORD: lightdash
      POSTGRES_DB: lightdash
    volumes:
      - lightdash_db:/var/lib/postgresql/data

  lightdash:
    image: lightdash/lightdash:latest
    depends_on:
      - lightdash_db
    volumes:
      - ./dbt:/usr/app/dbt
      - ./data:/usr/app/data
    environment:
      LIGHTDASH_SECRET: supersecret
      PGHOST: lightdash_db
      PGPORT: 5432
      PGUSER: lightdash
      PGPASSWORD: lightdash
      PGDATABASE: lightdash
      DBT_PROJECT_DIR: /usr/app/dbt
      # Use a built-in local S3 server for development to avoid extra
      # configuration. This prevents the runtime error about missing S3
      # settings when starting the Lightdash container.
      S3_MOCK: "true"
      # Provide explicit S3 parameters to satisfy newer Lightdash versions
      # that require these variables even when using the built-in mock.
      S3_ENDPOINT: http://localhost:9000
      S3_BUCKET: lightdash
      S3_REGION: us-east-1
      S3_ACCESS_KEY_ID: minio
      S3_SECRET_ACCESS_KEY: minio123
    ports:
        - "8080:8080"

  docs:
    build: .
    working_dir: /app/dbt
    command: bash -c "dbt docs generate && dbt docs serve --port 8081 --host 0.0.0.0"

    volumes:
      - ./data:/app/data
    ports:
      - "8081:8081"
    environment:
      DBT_PROFILES_DIR: /app/dbt

volumes:
  lightdash_db:
