version: '3.8'
services:
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
  dwh:
    build: .
    volumes:
      - ./data:/app/data
    command: dagster dev -m dagster_pipeline --host 0.0.0.0
    ports:
      - "3000:3000"
    environment:
      DBT_PROFILES_DIR: /app/dbt
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: warehouse

  lightdash_db:
    image: postgres:13
    environment:
      POSTGRES_USER: lightdash
      POSTGRES_PASSWORD: lightdash
      POSTGRES_DB: lightdash
    volumes:
      - lightdash_db:/var/lib/postgresql/data

  lightdash:
    image: lightdash/lightdash:latest
    depends_on:
      - lightdash_db
    volumes:
      - ./dbt:/usr/app/dbt
      - ./data:/usr/app/data
    environment:
      LIGHTDASH_SECRET: supersecret
      PGHOST: lightdash_db
      PGPORT: 5432
      PGUSER: lightdash
      PGPASSWORD: lightdash
      PGDATABASE: lightdash
      DBT_PROJECT_DIR: /usr/app/dbt

      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: lightdash
      S3_REGION: us-east-1
      S3_FORCE_PATH_STYLE: "true"

    ports:
        - "8080:8080"

  docs:
    build: .
    working_dir: /app/dbt
    command: bash -c "dbt docs generate && dbt docs serve --port 8081 --host 0.0.0.0"

    volumes:
      - ./data:/app/data
    ports:
      - "8081:8081"
    environment:
      DBT_PROFILES_DIR: /app/dbt

volumes:
  lightdash_db:
  minio_data:
