version: '3.8'
services:
  dwh:
    build: .
    volumes:
      - ./data:/app/data
    command: python orchestrator.py

  webui:
    image: ghcr.io/duckdb/duckdb-wasm-shell:latest
    ports:
      - "8080:8080"
