version: '3.8'
services:
  dwh:
    build: .
    volumes:
      - ./data:/app/data
    command: dagster dev -m dagster_pipeline --host 0.0.0.0
    ports:
      - "3000:3000"
    environment:
      DBT_PROFILES_DIR: /app/dbt

  superset_db:
    image: postgres:13
    environment:
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_DB: superset
    volumes:
      - superset_db:/var/lib/postgresql/data

  superset_cache:
    image: redis:latest

  superset:
    image: apache/superset:latest
    depends_on:
      - superset_db
      - superset_cache
    environment:
      SUPERSET_SECRET_KEY: superset-secret
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://superset:superset@superset_db:5432/superset
      REDIS_HOST: superset_cache
      SUPERSET_CONFIG_PATH: /app/pythonpath/superset_config.py
      ADMIN_USERNAME: max
      ADMIN_FIRSTNAME: Max
      ADMIN_LASTNAME: Account
      ADMIN_EMAIL: max@example.com
      ADMIN_PASSWORD: admin
    command: >-
      /bin/bash -c "\
      superset db upgrade && \
      superset fab create-admin \
        --username $ADMIN_USERNAME \
        --firstname $ADMIN_FIRSTNAME \
        --lastname $ADMIN_LASTNAME \
        --email $ADMIN_EMAIL \
        --password $ADMIN_PASSWORD && \
      superset init && \
      superset run -h 0.0.0.0 -p 8088"
    ports:
      - "8080:8088"
    volumes:
      - ./superset_config.py:/app/pythonpath/superset_config.py

  docs:
    build: .
    working_dir: /app/dbt
    command: bash -c "dbt docs generate && dbt docs serve --port 8081 --host 0.0.0.0"

    volumes:
      - ./data:/app/data
    ports:
      - "8081:8081"
    environment:
      DBT_PROFILES_DIR: /app/dbt

volumes:
  superset_db:
  superset_cache:
