version: '3.8'
services:
  dwh:
    build: .
    volumes:
      - ./data:/app/data
    command: dagster dev -m dagster_pipeline --host 0.0.0.0
    ports:
      - "3000:3000"
    environment:
      DBT_PROFILES_DIR: /app/dbt

  lightdash_db:
    image: postgres:13
    environment:
      POSTGRES_USER: lightdash
      POSTGRES_PASSWORD: lightdash
      POSTGRES_DB: lightdash
    volumes:
      - lightdash_db:/var/lib/postgresql/data

  lightdash:
    image: lightdash/lightdash:latest
    depends_on:
      - lightdash_db
    volumes:
      - ./dbt:/usr/app/dbt
      - ./data:/usr/app/data
    environment:
      LIGHTDASH_SECRET: supersecret
      PGHOST: lightdash_db
      PGPORT: 5432
      PGUSER: lightdash
      PGPASSWORD: lightdash
      PGDATABASE: lightdash
      DBT_PROJECT_DIR: /usr/app/dbt
    ports:
      - "8080:8080"

  docs:
    build: .
    working_dir: /app/dbt
    command: bash -c "dbt docs generate && dbt docs serve --port 8081 --host 0.0.0.0"

    volumes:
      - ./data:/app/data
    ports:
      - "8081:8081"
    environment:
      DBT_PROFILES_DIR: /app/dbt

volumes:
  lightdash_db:
