version: '3.8'
services:
  dwh:
    build: .
    volumes:
      - ./data:/app/data
    command: dagster dev -m dagster_pipeline --host 0.0.0.0

  webui:
    image: duckdb/duckdb-wasm-shell:latest
    ports:
      - "8080:8080"
