models:
  - name: orders_enriched
    active: true
  - name: sales_by_country
    active: true
  - name: wheat_weather
    active: true

sources:
  - name: commodities
    fetcher: sources.commodities.fetch
    schedule: "hourly"
    models:
      - orders_enriched
      - sales_by_country
      - wheat_weather
  - name: weather
    fetcher: sources.weather.fetch
    schedule: "hourly"
    models:
      - wheat_weather
