models:
  - name: player_stats
    active: true
  - name: player_efficiency
    active: true

sources:
  - name: basketball_stats
    fetcher: sources.basketball.fetch
    schedule: "daily"
    models:
      - player_stats
      - player_efficiency
