models:
  - name: orders_enriched
    active: true
  - name: sales_by_country
    active: true

sources:
  - name: commodities
    fetcher: sources.commodities.fetch
    schedule: "hourly"
    models:
      - orders_enriched
      - sales_by_country

