name: 'mini_dwh'
version: '1.0'
config-version: 2

profile: 'mini_dwh'

model-paths: ['models']
seed-paths: ['seeds']

target-path: 'target'

models:
  mini_dwh:
    bronze:
      +schema: bronze
      materialized: table
    silver:
      +schema: silver
      materialized: table
    gold:
      +schema: gold
      materialized: table
